routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    return view('welcome');
});

Route::get('/o_nas', 'AboutUsController@index')->name('about_us');
Route::get('/pytania', 'QuestionsController@index');
Route::get('/pytania/{id}', 'QuestionsController@show');

Route::get('/', 'IndexController@index')->name('index');

Route::group(['prefix' => '/admin', 'namespace' => 'Admin', 'middleware' => ['auth.basic']], function () {
    Route::get('/', 'IndexController@index');
    Route::get('/hello', 'IndexController@hello');

    Route::resource('tags', 'TagController');
    Route::resource('types', 'SheetTypeController');
    Route::resource('tiers', 'SheetTierController');
    Route::resource('versions', 'SheetVersionController');
    Route::resource('subjects', 'SubjectController');
    Route::resource('subjects.descriptions', 'Subject\DescriptionController');

    Route::group(['prefix' => 'inputs', 'as' => 'inputs.'], function (){
        Route::resource('types', 'InputTypeController');
    });

    Route::group(['prefix' => 'inputs/groups', 'as' => 'inputs.groups.'], function (){
        Route::resource('types', 'InputGroupTypeController');
    });

    Route::resource('sheets', 'SheetController');
    Route::resource('sheets.questions', 'QuestionController');
    Route::resource('sheets.questions.tags', 'Question\\TagController');
    Route::resource('sheets.questions.contents', 'Question\\ContentController');
    Route::resource('sheets.questions.substitutes', 'Question\\SubstituteController');
    Route::resource('sheets.questions.substitutes.contents', 'Question\\Substitute\\ContentController');
    Route::resource('sheets.questions.substitutes.inputGroups', 'Question\\Substitute\\InputGroupController');
    Route::resource('sheets.questions.substitutes.inputs', 'Question\\Substitute\\InputController');
    Route::resource('sheets.questions.substitutes.rewards', 'Question\\Substitute\\RewardController');
    Route::resource('sheets.questions.substitutes.inputs.corrects', 'Question\\Substitute\\InputCorrectController');
    Route::resource('sheets.questions.substitutes.inputs.rewards', 'Question\\Substitute\\InputRewardController');

    Route::group(['prefix' => 'sheets/{sheet}/questions/{question}/editor', 'as' => 'sheets.questions.editor.'], function () {
        Route::get('/', 'QuestionEditorController@index')->name('index');
    });
});

Route::group([
    'prefix' => '{subject}',
    'as' => 'users.subjects.',
    'middleware' => [
        'subject.exists'
    ]
], function (){
    Route::get('/', 'SubjectController@show')->name('show');

    Route::group([
        'prefix' => '/arkusze',
        'as' => 'sheets.',
        'guard' => 'guest'
    ], function (){
        Route::get('/', 'SheetsController@index')->name('index');
        Route::get('/{release}', 'SheetsController@show')->name('show');
        Route::post('/{release}', 'SheetsController@check')->name('check');
    });

    Route::group([
        'prefix' => '/pytania',
        'as' => 'questions.',
        'guard' => 'guest'
    ], function (){
        Route::get('/', 'QuestionsController@index')->name('index');
        Route::get('/{slug}', 'QuestionsController@show')->name('show');
        Route::post('/{slug}', 'QuestionsController@check')->name('check');
    });
});

resources/views/admin/versions/create.blade.php
@extends('layouts.admin', ['title' => 'Dodaj nowy typ matur'])

@section('content')
    <div class="button-container">
        <a class="button" href="{{ route('versions.index') }}">Wróć</a>
    </div>
    @if($errors->any())
        <div class="notifier">
            <div class="notifier-header">
                <h3 class="notifier-title">Powiadomienia</h3>
            </div>
            <div class="notifier-body">
                @foreach($errors->all() as $error)
                    <span class="notifier-item">{{ $error }}</span>
                @endforeach
            </div>
        </div>
    @endif
    <div class="form-container">
        <form class="form" action="{{ route('versions.store') }}" method="post">
            @csrf
            <label class="input-container">
                Opis
                <input name="description" class="input-admin-text" type="text">
            </label>
            <label class="input-container">
                Krótki opis
                <input name="short_description" class="input-admin-text" type="text">
            </label>
            <label class="input-container input-checkbox-container">
                Czy wyświetlać opis?
                <input name="display_stat" class="input-checkbox" type="checkbox">
                <span class="input-checkmark"></span>
            </label>
            <label class="input-container input-checkbox-container">
                Czy wyświetlać krótki opis?
                <input name="display_name" class="input-checkbox" type="checkbox">
                <span class="input-checkmark"></span>
            </label>
            <div class="button-container">
                <button class="button" type="submit">
                    Dodaj
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/versions/edit.blade.php
@extends('layouts.admin', ['title' => 'Edytuj typ matur'])

@section('content')
    <div class="button-container">
        <a class="button" href="{{ route('versions.index') }}">Wróć</a>
    </div>
    @if($errors->any())
        <div class="notifier">
            <div class="notifier-header">
                <h3 class="notifier-title">Powiadomienia</h3>
            </div>
            <div class="notifier-body">
                @foreach($errors->all() as $error)
                    <span class="notifier-item">{{ $error }}</span>
                @endforeach
            </div>
        </div>
    @endif
    <div class="form-container">
        <form class="form" action="{{ route('versions.update', $version->id) }}" method="post">
            @csrf
            @method('PUT')
            <label class="input-container">
                Opis
                <input name="description" class="input-admin-text" type="text" value="{{ $version->description }}">
            </label>
            <label class="input-container">
                Krótki opis
                <input name="short_description" class="input-admin-text" type="text" value="{{ $version->short_description }}">
            </label>
            <label class="input-container input-checkbox-container">
                Czy wyświetlać opis?
                <input name="display_stat" class="input-checkbox" type="checkbox" {{ $version->display_stat ? 'checked' : '' }}>
                <span class="input-checkmark"></span>
            </label>
            <label class="input-container input-checkbox-container">
                Czy wyświetlać krótki opis?
                <input name="display_name" class="input-checkbox" type="checkbox" {{ $version->display_name ? 'checked' : '' }}>
                <span class="input-checkmark"></span>
            </label>
            <div class="button-container">
                <button class="button" type="submit">
                    Edytuj
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/versions/index.blade.php
@extends('layouts.admin', ['title' => 'Wersje matur'])

@section('content')
    <div class="button-container">
        <a class="button" href="{{ route('versions.create') }}">Dodaj nową wersję</a>
    </div>
    <table class="table">
        <tr class="table-head">
            <th>ID</th>
            <th>Opis</th>
            <th>Krótki opis</th>
            <th>Wyświetlać opis?</th>
            <th>Wyświetlać krótki opis?</th>
            <th>Akcje</th>
        </tr>
        @foreach($versions as $version)
            <tr>
                <td>{{ $version->id }}</td>
                <td>{{ $version->description }}</td>
                <td>{{ $version->short_description }}</td>
                <td>{{ $version->display_stat ? 'Tak' : 'Nie' }}</td>
                <td>{{ $version->display_name ? 'Tak' : 'Nie' }}</td>
                <td>
                    <button class="mini-link mini-link-delete" type="submit" form="version-delete-{{ $version->id }}"></button>
                    <form id="version-delete-{{ $version->id }}" method="post" action="{{ route('versions.destroy', $version->id) }}" style="display: none;">
                        @csrf
                        @method('DELETE')
                    </form>
                    <a class="mini-link mini-link-edit" href="{{ route('versions.edit', $version->id) }}"></a>
                </td>
            </tr>
        @endforeach
    </table>
@endsection