routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    return view('welcome');
});

Route::get('/o_nas', 'AboutUsController@index')->name('about_us');
Route::get('/pytania', 'QuestionsController@index');
Route::get('/pytania/{id}', 'QuestionsController@show');

Route::get('/', 'IndexController@index')->name('index');

Route::group(['prefix' => '/admin', 'namespace' => 'Admin', 'middleware' => ['auth.basic']], function () {
    Route::get('/', 'IndexController@index');
    Route::get('/hello', 'IndexController@hello');

    Route::resource('tags', 'TagController');
    Route::resource('types', 'SheetTypeController');
    Route::resource('tiers', 'SheetTierController');
    Route::resource('versions', 'SheetVersionController');
    Route::resource('subjects', 'SubjectController');
    Route::resource('subjects.descriptions', 'Subject\DescriptionController');

    Route::group(['prefix' => 'inputs', 'as' => 'inputs.'], function (){
        Route::resource('types', 'InputTypeController');
    });

    Route::group(['prefix' => 'inputs/groups', 'as' => 'inputs.groups.'], function (){
        Route::resource('types', 'InputGroupTypeController');
    });

    Route::resource('sheets', 'SheetController');
    Route::resource('sheets.questions', 'QuestionController');
    Route::resource('sheets.questions.tags', 'Question\\TagController');
    Route::resource('sheets.questions.contents', 'Question\\ContentController');
    Route::resource('sheets.questions.substitutes', 'Question\\SubstituteController');
    Route::resource('sheets.questions.substitutes.contents', 'Question\\Substitute\\ContentController');
    Route::resource('sheets.questions.substitutes.inputGroups', 'Question\\Substitute\\InputGroupController');
    Route::resource('sheets.questions.substitutes.inputs', 'Question\\Substitute\\InputController');
    Route::resource('sheets.questions.substitutes.rewards', 'Question\\Substitute\\RewardController');
    Route::resource('sheets.questions.substitutes.inputs.corrects', 'Question\\Substitute\\InputCorrectController');
    Route::resource('sheets.questions.substitutes.inputs.rewards', 'Question\\Substitute\\InputRewardController');

    Route::group(['prefix' => 'sheets/{sheet}/questions/{question}/editor', 'as' => 'sheets.questions.editor.'], function () {
        Route::get('/', 'QuestionEditorController@index')->name('index');
    });
});

Route::group([
    'prefix' => '{subject}',
    'as' => 'users.subjects.',
    'middleware' => [
        'subject.exists'
    ]
], function (){
    Route::get('/', 'SubjectController@show')->name('show');

    Route::group([
        'prefix' => '/arkusze',
        'as' => 'sheets.',
        'guard' => 'guest'
    ], function (){
        Route::get('/', 'SheetsController@index')->name('index');
        Route::get('/{release}', 'SheetsController@show')->name('show');
        Route::post('/{release}', 'SheetsController@check')->name('check');
    });

    Route::group([
        'prefix' => '/pytania',
        'as' => 'questions.',
        'guard' => 'guest'
    ], function (){
        Route::get('/', 'QuestionsController@index')->name('index');
        Route::get('/{slug}', 'QuestionsController@show')->name('show');
        Route::post('/{slug}', 'QuestionsController@check')->name('check');
    });
});

app/Models/Subject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

/**
 * @property integer $id
 * @property string $name
 * @property string $icon
 * @property string $slug
 * @property string $theme
 * @property boolean $enabled
 * @property Sheet[]|Collection $sheets
 * @property TagGroup[] $tagGroups
 * @property SubjectDescription|null $description
 * @property integer $total_sheet_count
 */
class Subject extends Model
{
    use HasSlug;
    /**
     * The "type" of the auto-incrementing ID.
     * 
     * @var string
     */
    protected $keyType = 'integer';

    /**
     * @var array
     */
    protected $fillable = ['name', 'icon', 'enabled', 'theme'];

    protected $hidden = [

    ];

    /**
     * Indicates if the model should be timestamped.
     * 
     * @var bool
     */
    public $timestamps = false;

    /**
     * The storage format of the model's date columns.
     * 
     * @var string
     */
    protected $dateFormat = 'U';

    /**
     * The connection name for the model.
     * 
     * @var string
     */
    protected $connection = 'mysql';

    public function getTotalSheetsCountAttribute()
    {
        return $this->sheets->sum('count');
    }

    public function getTotalResolvedSheetsCountAttribute()
    {
        return $this->sheets->sum('resolved_sheets_count');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function sheets()
    {
        return $this->hasMany('App\Models\Sheet');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tagGroups()
    {
        return $this->hasMany('App\Models\TagGroup');
    }

    public function description()
    {
        return $this->hasOne(SubjectDescription::class, 'subject_id', 'id');
    }

    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native versions.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/user/about_us.blade.php
@extends('layouts.app')

@section('content')
    <div style="background: white; padding: 2em;text-align: justify;">
        <h1>
            O mnie
        </h1>
        <p>
            <img style="margin-left: 1rem;" class="image image-profile" src="{{ asset('images/my_img.jpg') }}" alt="">
            Cześć! Jestem <b>Maciej</b>, mam 21 lat a ta strona to obecnie moje największe dzieło. Jedyne które właściwie ukończyłem, lecz również jedyne przy którym nikt mi nie pomagał. Nie licząc samego pomysłu, który zawdzięczam
            swojej serdecznej koleżance, która niestety nie zgodziła się abym ją tutaj umieścił, ale jeśli to czyta, to chcę żeby wiedziała, że jestem jej ogromnie wdzięczny za to co dla mnie zrobiła. Bez niej tej
            strony by po prostu nie było.
        </p>
        <p>
            Na codzień zajmuję się tym co najbardziej lubię, czyli właśnie <b>programowaniem</b> i robiłem to już od dzieciństwa, lecz na poważnie zacząłem się tym interesować dopiero w 2 klasie technikum, po jednej
            z lekcji z <i>projektowania stron internetowych</i>. Od razu wiedziałem, że będzie to coś, czym będę chciał się zajmować już do końca życia.
        </p>
        <p>
            Moim największym hobby zaraz po programowaniu, to <b>psychologia</b>. Dzięki niej czuję się uwrażliwiony na wiele procesów zachodzących w naszych mózgach. Z dziedziny posiadanych umiejętności i wiedzy,
            chyba najciekawszym okazał się efekt <i>Krugera-Dunninga</i>, przez co nie przepadam odpowiadać na pytania w stylu <cite>"Jak w skali od 1-10 oceniasz swoje umiejętności w dziedzinie x?"</cite>, w końcu skąd
            mam wiedzieć, że osoba której udzielam odpowiedzi, w ogóle wie o istnieniu takiego procesu?
        </p>
        <p>Oprócz tego jest jeszcze sporo rzeczy którymi lubię się zajmować, ale nie widzę sensu wymieniania tutaj wszystkiego, dlatego jeśli ktoś jest zainteresowany,
            zapraszam do wysyłania wiadomości na adres <a href="mailto:kromacie@gmail.com">kromacie@gmail.com</a>, a oprócz tego zapraszam do testowania strony!
        </p>
        <h3>
            Dla potencjalnych pracodawców
        </h3>
        <p>
            Ta strona została stworzona przez <i>backend developera</i> w języku <b>PHP 7.3</b> przy użyciu frameworka <b>Laravel 5.8</b>.
        </p>
        <p>
            Stack technologiczny
        </p>
        <ul>
            <li>PHP 7.3</li>
            <li>Redis pub/sub</li>
            <li>Redis cache</li>
            <li>Git</li>
            <li>Laravel 5.8</li>
            <li>Laravel Queue</li>
            <li>Laravel Broadcasting</li>
            <li>Laravel Eloquent</li>
            <li>Laravel Echo</li>
            <li>Markdown</li>
            <li>Socket.io</li>
            <li>MySQL</li>
            <li>jQuery</li>
            <li>jQuery - Ajax</li>
            <li>Css - Flexbox</li>
            <li>Sass</li>
            <li>Blade</li>
        </ul>
        <p>
            Kod udostępnię na życzenie jeśli będzie to niezbędne w procesie rekrutacji.
        </p>
        <h3></h3>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <ul class="breadcrumb">
        <li class="breadcrumb-item selected">
            <i class="icon icon-home"></i>
        </li>
    </ul>

    <div class="section">
        <div class="section-header">
            <h1 class="title title-primary title-gradient"><i class="title-icon icon icon-flag"></i>Rozpocznij przygodę!</h1>
        </div>
        <div class="section-body">
            <article class="article">
                <article class="article-body">
                    <p class="article-text article-text-intended">
                        Chcesz rozwiązywać <b>arkusze</b> lub <b>zadania</b> maturalne z ostatnich lat, ale nie znalazłeś miejsca gdzie mógłbyś zrobić to online? Jeśli tak, to dobrze trafiłeś.
                        Posiadamy zadania które nie ograniczają się do klasycznego <i>wybierz A) lub B)</i>, lecz cały system, który integruje ze sobą różne wersje zadań i sposobów ich rozwiązywania!
                    </p>
                    <p>
                        Są to między innymi:
                    </p>
                    <ul>
                        <li>Zadania wielokrotnego wyboru</li>
                        <li>Zadania jednokrotnego wyboru</li>
                        <li>Podaj definicje</li>
                        <li>Uzupełnij wzór</li>
                    </ul>
                    <p>
                        Strona jest obecnie w wersji beta.
                    </p>
                </article>
            </article>
        </div>
    </div>
    <div class="section">
        <div class="section-header">
            <h1 class="title title-primary title-gradient"><i class="title-icon icon icon-sheet"></i>Arkusze</h1>
        </div>
        <div class="section-body">
            <div class="article-list">
                <article class="article">
                    <div class="article-body">
                        <p class="article-text article-text-intended">
                            Posiadamy <b>arkusze maturalne</b> sprzed kilku lat, są one na bieżąco aktualizowane i sprawdzanie. Właśnie tutaj możesz sprawdzić swoją wiedzę rozwiązując <b>interaktywne testy</b>, porównaj je z innymi i zobacz na jakim wypadasz poziomie! Możesz również wybrać losowe pytanie.
                        </p>
                    </div>
                </article>
            </div>
        </div>
    </div>
    @isset($subjects)
    <div class="section">
        <div class="section-body card-container">
            @foreach($subjects->reverse() as $subject)
            <div class="card col card-primary highlight-box">
                <div class="card-header">
                    <h2 class="title title-{{ $subject->theme }} title-inline">
                        <i class="title-icon icon {{ $subject->icon }}"></i>{{ $subject->name }}
                    </h2>
                </div>
                <div class="card-body">
                    <div class="mini-cards">
                        <div class="mini-cards-header">
                            <ul id="calendar-bar-{{ $subject->id }}" class="calendar-bar calendar-bar-{{ $subject->theme }}">
                                <li class="calendar-bar-icon icon icon-calendar"></li>
                                @foreach($subject->sheets as $sheet)
                                    <li data-sheet="{{ $sheet->id }}" data-subject="{{ $subject->id }}" id="mini-card-calendar-{{ $sheet->id }}" class="calendar-bar-item">{{ $sheet->year }}</li>
                                @endforeach
                            </ul>
                        </div>
                        <div id="mini-cards-body-list-{{ $subject->id }}" class="mini-cards-body-list">
                            @foreach($subject->sheets as $sheet)
                                <div id="mini-card-body-{{ $sheet->id }}" class="mini-cards-body">
                                    <h3 class="mini-cards-body-title">
                                        Statystyki
                                    </h3>
                                    <div class="mini-cards-stats stats stats-{{ $subject->theme }}">
                                        <div class="stats-row">
                                            <div class="stats-title">Rozwiązanych arkuszy</div>
                                            <div class="stats-bar">
                                                <span class="stats-progress-bar" style="width: {{ $sheet->percentageOfTotalResolvedSheets($subject->total_resolved_sheets_count) }}%">{{ $sheet->resolved_sheets_count }}</span>
                                            </div>
                                        </div>
                                        <div class="stats-row">
                                            <div class="stats-title">Średni wynik</div>
                                            <div class="stats-bar">
                                                <span class="stats-progress-bar" style="width: {{ $sheet->percentage_result }}%">{{ $sheet->percentage_result }}%</span>
                                            </div>
                                        </div>
                                        <div class="stats-row">
                                            <div class="stats-title">Ilość arkuszy</div>
                                            <div class="stats-bar">
                                                <span class="stats-progress-bar" style="width: {{ $sheet->percentageOfTotalSheets($subject->total_sheets_count) }}%">{{ $sheet->count }}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <button class="mini-cards-button button button-{{ $subject->theme }} button-inline" onclick="window.location.href = `{{ route('users.subjects.sheets.index', [$subject->slug, $sheet->slug, 'years' => [$sheet->year]]) }}`">Rozwiązuj</button>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
            @endforeach

        </div>
    </div>
    @endisset
@endsection

@section('scripts')
    <script type="text/javascript">
        $(function () {
            init();
        });

        function init() {
            $('.calendar-bar').each(function (index, element) {
                let item = $(element).find('.calendar-bar-item').first();

                select(item.data('subject'), item.data('sheet'))
            });
        }

        function select(subject, sheet) {
            uncheck(subject);
            $('#mini-card-calendar-' + sheet).addClass('selected');
            $('#mini-card-body-' + sheet).addClass('is-visible');
        }

        function uncheck(subject) {
            $('#mini-cards-body-list-' + subject + ' .mini-cards-body').removeClass('is-visible');
            $('#calendar-bar-' + subject + ' .calendar-bar-item').removeClass('selected');
        }

        $('.calendar-bar-item').on('click', function () {
            let element = $(this);

            console.log(element);

            select(element.data('subject'), element.data('sheet'));
        });
    </script>
@endsection

@section('footer')
    <footer class="footer-container">
        <div class="footer container">
            <div class="flex flex-row-lg flex-col">
                <div class="col col-4">
                    <div class="footer-head">
                        <h3>Kontakt</h3>
                        <p>
                            kromacie@gmail.com
                        </p>
                    </div>
                </div>
                <div class="col col-4">
                    <div class="footer-head">
                        <h3>Twórca</h3>
                        <p>
                            Maciej Król
                        </p>
                    </div>
                </div>
                <div class="col col-4">
                    <div class="footer-head">
                        <h3>Licencja</h3>
                        <p>
                            Beer-ware
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
@endsection

resources/views/user/subject.blade.php
@extends('layouts.app')

@section('content')
    <ul class="breadcrumb">
        <li class="breadcrumb-item selected">
            <a href="{{ route('index') }}" class="icon icon-home breadcrumb-link"></a>
        </li>
        <li class="breadcrumb-item"><a class="breadcrumb-link" href="{{ route('users.subjects.show', $subject->slug) }}"><i class="breadcrumb-icon icon {{ $subject->icon }}"></i>{{ $subject->name }}</a></li>
    </ul>
    @isset($subject->description)
        <div class="section">
            <div class="section-header">
                <h1 class="title title-primary title-gradient">{{ $subject->name }}</h1>
            </div>
            <div class="section-body">
                <div class="article-list">
                    <article class="article highlight-box">
                        <div class="article-body">
                            <div class="article-text article-text-intended">
                                @markdown($subject->description->content)
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    @endisset
    <div class="section">
        <div class="section-body card-container flex flex-col flex-row-xl minimal-cards">
            <div class="minimal-card minimal-card-primary minimal-card-media col">
                <div class="minimal-card-header">
                    <h1 class="minimal-card-title">
                        Arkusze
                    </h1>
                </div>
                <div class="minimal-card-body">
                    <span class="minimal-card-option col">
                        <span class="minimal-card-number">{{ $sheet_count }}</span>
                        <span class="minimal-card-description">Ilość arkuszy</span>
                    </span>
                    <span class="minimal-card-option col">
                            <span class="minimal-card-number">{{ $resolved_sheets }}</span>
                            <span class="minimal-card-description">Rozwiązanych arkuszy</span>
                        </span>
                    <span class="minimal-card-option col">
                        <span id="now_solving_sheet" class="minimal-card-number">
                            {{ $sheet_users }}
                        </span>
                        <span class="minimal-card-description">Aktualnie rozwiązywanych</span>
                    </span>
                </div>
                <div class="minimal-card-footer">
                    <a href="{{ route('users.subjects.sheets.index', $subject->slug) }}" class="minimal-card-button button button-inline">Rozwiązuj</a>
                </div>
            </div>
            <div class="minimal-card minimal-card-primary col">
                <div class="minimal-card-header">
                    <h1 class="minimal-card-title">
                        Zadania
                    </h1>
                </div>
                <div class="minimal-card-body">
                        <span class="minimal-card-option col">
                            <span class="minimal-card-number">{{ $question_count }}</span>
                            <span class="minimal-card-description">Ilość zadań</span>
                        </span>
                    <span class="minimal-card-option col">
                            <span class="minimal-card-number">{{ $resolved_questions }}</span>
                            <span class="minimal-card-description">Rozwiązanych zadań</span>
                        </span>
                    <span class="minimal-card-option col">
                            <span class="minimal-card-number">
                                {{ $question_users }}
                            </span>
                            <span class="minimal-card-description">Aktualnie rozwiązywanych</span>
                        </span>
                </div>
                <div class="minimal-card-footer">
                    <a href="{{ route('users.subjects.questions.index', $subject->slug) }}" class="minimal-card-button button button-inline">Rozwiązuj</a>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript">

    </script>
@endsection