routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    return view('welcome');
});

Route::get('/o_nas', 'AboutUsController@index')->name('about_us');
Route::get('/pytania', 'QuestionsController@index');
Route::get('/pytania/{id}', 'QuestionsController@show');

Route::get('/', 'IndexController@index')->name('index');

Route::group(['prefix' => '/admin', 'namespace' => 'Admin', 'middleware' => ['auth.basic']], function () {
    Route::get('/', 'IndexController@index');
    Route::get('/hello', 'IndexController@hello');

    Route::resource('tags', 'TagController');
    Route::resource('types', 'SheetTypeController');
    Route::resource('tiers', 'SheetTierController');
    Route::resource('versions', 'SheetVersionController');
    Route::resource('subjects', 'SubjectController');
    Route::resource('subjects.descriptions', 'Subject\DescriptionController');

    Route::group(['prefix' => 'inputs', 'as' => 'inputs.'], function (){
        Route::resource('types', 'InputTypeController');
    });

    Route::group(['prefix' => 'inputs/groups', 'as' => 'inputs.groups.'], function (){
        Route::resource('types', 'InputGroupTypeController');
    });

    Route::resource('sheets', 'SheetController');
    Route::resource('sheets.questions', 'QuestionController');
    Route::resource('sheets.questions.tags', 'Question\\TagController');
    Route::resource('sheets.questions.contents', 'Question\\ContentController');
    Route::resource('sheets.questions.substitutes', 'Question\\SubstituteController');
    Route::resource('sheets.questions.substitutes.contents', 'Question\\Substitute\\ContentController');
    Route::resource('sheets.questions.substitutes.inputGroups', 'Question\\Substitute\\InputGroupController');
    Route::resource('sheets.questions.substitutes.inputs', 'Question\\Substitute\\InputController');
    Route::resource('sheets.questions.substitutes.rewards', 'Question\\Substitute\\RewardController');
    Route::resource('sheets.questions.substitutes.inputs.corrects', 'Question\\Substitute\\InputCorrectController');
    Route::resource('sheets.questions.substitutes.inputs.rewards', 'Question\\Substitute\\InputRewardController');

    Route::group(['prefix' => 'sheets/{sheet}/questions/{question}/editor', 'as' => 'sheets.questions.editor.'], function () {
        Route::get('/', 'QuestionEditorController@index')->name('index');
    });
});

Route::group([
    'prefix' => '{subject}',
    'as' => 'users.subjects.',
    'middleware' => [
        'subject.exists'
    ]
], function (){
    Route::get('/', 'SubjectController@show')->name('show');

    Route::group([
        'prefix' => '/arkusze',
        'as' => 'sheets.',
        'guard' => 'guest'
    ], function (){
        Route::get('/', 'SheetsController@index')->name('index');
        Route::get('/{release}', 'SheetsController@show')->name('show');
        Route::post('/{release}', 'SheetsController@check')->name('check');
    });

    Route::group([
        'prefix' => '/pytania',
        'as' => 'questions.',
        'guard' => 'guest'
    ], function (){
        Route::get('/', 'QuestionsController@index')->name('index');
        Route::get('/{slug}', 'QuestionsController@show')->name('show');
        Route::post('/{slug}', 'QuestionsController@check')->name('check');
    });
});

resources/views/layouts/admin.blade.php
<html lang="pl">
<head>
    <title>Biolchem</title>
    <link rel="stylesheet" href="{{ asset('css/admin.css') }}">
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body>
<div class="flex flex-row">
    <div class="nav col-2">
        <div class="nav-header">
            <h1 class="nav-title">Panel</h1>
        </div>
        <div class="nav-body">
            <ul class="nav-list">
                <li class="nav-item expand-toggler" data-target="#subjects-nav">Przedmioty</li>
                <li id="subjects-nav" class="nav-expand-target expand-target">
                    <ul class="nav-list">
                        <li class="nav-item"><a class="nav-link" href="{{ route('subjects.index') }}">Przeglądaj</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('subjects.create') }}">Dodaj</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav-list">
                <li class="nav-item expand-toggler" data-target="#sheets-nav">Arkusze</li>
                <li id="sheets-nav" class="nav-expand-target expand-target">
                    <ul class="nav-list">
                        <li class="nav-item"><a class="nav-link" href="{{ route('sheets.index') }}">Przeglądaj</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('sheets.create') }}">Dodaj</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav-list">
                <li class="nav-item expand-toggler" data-target="#versions-nav">Wersje arkuszy</li>
                <li id="versions-nav" class="nav-expand-target expand-target">
                    <ul class="nav-list">
                        <li class="nav-item"><a class="nav-link" href="{{ route('versions.index') }}">Przeglądaj</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('versions.create') }}">Dodaj</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav-list">
                <li class="nav-item expand-toggler" data-target="#tiers-nav">Poziomy arkuszy</li>
                <li id="tiers-nav" class="nav-expand-target expand-target">
                    <ul class="nav-list">
                        <li class="nav-item"><a class="nav-link" href="{{ route('tiers.index') }}">Przeglądaj</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('tiers.create') }}">Dodaj</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav-list">
                <li class="nav-item expand-toggler" data-target="#types-nav">Typy arkuszy</li>
                <li id="types-nav" class="nav-expand-target expand-target">
                    <ul class="nav-list">
                        <li class="nav-item"><a class="nav-link" href="{{ route('types.index') }}">Przeglądaj</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('types.create') }}">Dodaj</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav-list">
                <li class="nav-item expand-toggler" data-target="#tags-nav">Tagi</li>
                <li id="tags-nav" class="nav-expand-target expand-target">
                    <ul class="nav-list">
                        <li class="nav-item"><a class="nav-link" href="{{ route('tags.index') }}">Przeglądaj</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('tags.create') }}">Dodaj</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav-list">
                <li class="nav-item expand-toggler" data-target="#inputs-groups-types-nav">Typy grup inputów</li>
                <li id="inputs-groups-types-nav" class="nav-expand-target expand-target">
                    <ul class="nav-list">
                        <li class="nav-item"><a class="nav-link" href="{{ route('inputs.groups.types.index') }}">Przeglądaj</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('inputs.groups.types.create') }}">Dodaj</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav-list">
                <li class="nav-item expand-toggler" data-target="#inputs-types-nav">Typy inputów</li>
                <li id="inputs-types-nav" class="nav-expand-target expand-target">
                    <ul class="nav-list">
                        <li class="nav-item"><a class="nav-link" href="{{ route('inputs.types.index') }}">Przeglądaj</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('inputs.types.create') }}">Dodaj</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav-list">
                <li class="nav-item expand-toggler" data-target="#stats-nav">Statystyki</li>
                <li id="stats-nav" class="nav-expand-target expand-target">
                    <ul class="nav-list">
                        <li class="nav-item">Przeglądaj</li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-10">
        <div class="header">
            <h2 class="header-title">{{ $title }}</h2>
        </div>
        <section class="section">
            <div class="section-header">
                <h2 class="section-title">Zawartość</h2>
            </div>
            <div class="section-body">
                @section('content')
                    <span>Wybierz opcję z listy</span>
                @show
            </div>
        </section>
    </div>
</div>
<script src="{{ asset('js/app.js') }}"></script>
@section('scripts')

@show
</body>
</html>

resources/views/layouts/app.blade.php
<html lang="pl">
<head>
    <title>Biolchem</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body>

<div class="header-main">
    <div class="header-main-image"></div>
    <h1 class="header-main-logo">
        <i class="icon icon-seedling"></i> Biolchem
    </h1>
    <p class="header-main-description">Because we love science!</p>
</div>
<div class="nav-main">
    <ul class="nav-main-navbar">
        <li class="nav-main-item">
            <a href="{{ route('index') }}">Strona główna</a>
        </li>
        @foreach($subjects as $subject)
            <li class="nav-main-item">
                <a href="{{ route('users.subjects.show', $subject->slug) }}">
                    {{ $subject->name }}
                    @if($subject->icon)
                        <i class="nav-main-icon icon {{ $subject->icon }}"></i>
                    @endif
                </a>
            </li>
        @endforeach
        <li class="nav-main-item nav-main-item-disabled">
            <a href="#">Kontakt</a>
        </li>
        <li class="nav-main-item">
            <a href="{{ route('about_us') }}">O nas</a>
        </li>
    </ul>
</div>
<br />
<div class="container">
    @yield('content')
</div>

@yield('footer')

<script src="{{ asset('js/app.js') }}"></script>
@section('scripts')

@show
</body>
</html>