routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    return view('welcome');
});

Route::get('/o_nas', 'AboutUsController@index')->name('about_us');
Route::get('/pytania', 'QuestionsController@index');
Route::get('/pytania/{id}', 'QuestionsController@show');

Route::get('/', 'IndexController@index')->name('index');

Route::group(['prefix' => '/admin', 'namespace' => 'Admin', 'middleware' => ['auth.basic']], function () {
    Route::get('/', 'IndexController@index');
    Route::get('/hello', 'IndexController@hello');

    Route::resource('tags', 'TagController');
    Route::resource('types', 'SheetTypeController');
    Route::resource('tiers', 'SheetTierController');
    Route::resource('versions', 'SheetVersionController');
    Route::resource('subjects', 'SubjectController');
    Route::resource('subjects.descriptions', 'Subject\DescriptionController');

    Route::group(['prefix' => 'inputs', 'as' => 'inputs.'], function (){
        Route::resource('types', 'InputTypeController');
    });

    Route::group(['prefix' => 'inputs/groups', 'as' => 'inputs.groups.'], function (){
        Route::resource('types', 'InputGroupTypeController');
    });

    Route::resource('sheets', 'SheetController');
    Route::resource('sheets.questions', 'QuestionController');
    Route::resource('sheets.questions.tags', 'Question\\TagController');
    Route::resource('sheets.questions.contents', 'Question\\ContentController');
    Route::resource('sheets.questions.substitutes', 'Question\\SubstituteController');
    Route::resource('sheets.questions.substitutes.contents', 'Question\\Substitute\\ContentController');
    Route::resource('sheets.questions.substitutes.inputGroups', 'Question\\Substitute\\InputGroupController');
    Route::resource('sheets.questions.substitutes.inputs', 'Question\\Substitute\\InputController');
    Route::resource('sheets.questions.substitutes.rewards', 'Question\\Substitute\\RewardController');
    Route::resource('sheets.questions.substitutes.inputs.corrects', 'Question\\Substitute\\InputCorrectController');
    Route::resource('sheets.questions.substitutes.inputs.rewards', 'Question\\Substitute\\InputRewardController');

    Route::group(['prefix' => 'sheets/{sheet}/questions/{question}/editor', 'as' => 'sheets.questions.editor.'], function () {
        Route::get('/', 'QuestionEditorController@index')->name('index');
    });
});

Route::group([
    'prefix' => '{subject}',
    'as' => 'users.subjects.',
    'middleware' => [
        'subject.exists'
    ]
], function (){
    Route::get('/', 'SubjectController@show')->name('show');

    Route::group([
        'prefix' => '/arkusze',
        'as' => 'sheets.',
        'guard' => 'guest'
    ], function (){
        Route::get('/', 'SheetsController@index')->name('index');
        Route::get('/{release}', 'SheetsController@show')->name('show');
        Route::post('/{release}', 'SheetsController@check')->name('check');
    });

    Route::group([
        'prefix' => '/pytania',
        'as' => 'questions.',
        'guard' => 'guest'
    ], function (){
        Route::get('/', 'QuestionsController@index')->name('index');
        Route::get('/{slug}', 'QuestionsController@show')->name('show');
        Route::post('/{slug}', 'QuestionsController@check')->name('check');
    });
});

resources/views/admin/types/create.blade.php
@extends('layouts.admin', ['title' => 'Stwórz typ'])

@section('content')
    <div class="button-container">
        <a class="button" href="{{ route('types.index') }}">Wróć</a>
    </div>
    @if($errors->any())
        <div class="notifier">
            <div class="notifier-header">
                <h3 class="notifier-title">Powiadomienia</h3>
            </div>
            <div class="notifier-body">
                @foreach($errors->all() as $error)
                    <span class="notifier-item">{{ $error }}</span>
                @endforeach
            </div>
        </div>
    @endif
    <div class="form-container">
        <form class="form" action="{{ route('types.store') }}" method="post">
            @csrf
            <label class="input-container">
                Nazwa
                <input name="name" class="input-admin-text" type="text">
            </label>
            <div class="button-container">
                <button class="button" type="submit">
                    Dodaj
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/types/edit.blade.php
@extends('layouts.admin', ['title' => 'Edytuj typ'])

@section('content')
    <div class="button-container">
        <a class="button" href="{{ route('types.index') }}">Wróć</a>
    </div>
    @if($errors->any())
        <div class="notifier">
            <div class="notifier-header">
                <h3 class="notifier-title">Powiadomienia</h3>
            </div>
            <div class="notifier-body">
                @foreach($errors->all() as $error)
                    <span class="notifier-item">{{ $error }}</span>
                @endforeach
            </div>
        </div>
    @endif
    <div class="form-container">
        <form class="form" action="{{ route('types.update', $type->id) }}" method="post">
            @csrf
            @method('PUT')
            <label class="input-container">
                Nazwa
                <input name="name" class="input-admin-text" type="text" value="{{ $type->name }}">
            </label>
            <div class="button-container">
                <button class="button" type="submit">
                    Edytuj
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/types/index.blade.php
@extends('layouts.admin', ['title' => 'Typy arkuszy'])

@section('content')
    <div class="button-container">
        <a class="button" href="{{ route('types.create') }}">Dodaj typ</a>
    </div>
    <table class="table">
        <tr class="table-head">
            <th>ID</th>
            <th>Nazwa</th>
            <th>Actions</th>
        </tr>
        @foreach($types as $type)
            <tr>
                <td>{{ $type->id }}</td>
                <td>{{ $type->name }}</td>
                <td>
                    <button class="mini-link mini-link-delete" type="submit" form="tier-delete-{{ $type->id }}"></button>
                    <form id="tier-delete-{{ $type->id }}" method="post" action="{{ route('types.destroy', $type->id) }}" style="display: none;">
                        @csrf
                        @method('DELETE')
                    </form>
                    <a class="mini-link mini-link-edit" href="{{ route('types.edit', $type->id) }}"></a>
                </td>
            </tr>
        @endforeach
    </table>
@endsection